// modules/multiqc.nf
// Aggregates QC reports from Trim Galore/FastQC and alignment logs

process MULTIQC {

    label 'low'

    publishDir "${params.outdir}/multiqc", mode: 'copy'

    input:
    path fastqc_reports
    path alignment_logs

    output:
    path "multiqc_report.html", emit: report
    path "multiqc_data/",       emit: data

    script:
    """
    multiqc . \\
        --filename multiqc_report.html \\
        --title "Somatic Variant Calling QC Report" \\
        --comment "Generated by nextflow-somatic-variant-demo"
    """
}
